### ISSUE TITLE
array-1-function issue

### ISSUE THREAD

**Issue by superpikar** [renaldypermana/php-logic#1]
```
function jumlah($input,$angka)
	{
		$res= -1;
		foreach ($input as $key ) {
			$jumlah=$key * $angka;
			echo $jumlah. "</br>";
	}
	}
	echo jumlah($input,3);
```
karena di dalam fungsi sudah ada echo untuk menampilkan hasilnya. maka ketika pemanggilan fungsi tidak diperlukan echo lagi

**Comment by renaldypermana** [comment]
![image](https://user-images.githubusercontent.com/37020760/66108979-e6944f80-e5ed-11e9-8786-4d86a1667aee.png)
![image](https://user-images.githubusercontent.com/37020760/66109015-f7dd5c00-e5ed-11e9-917b-8dc7af209aad.png)
