### ISSUE TITLE
array-2-function issue

### ISSUE THREAD

**Issue by superpikar** [renaldypermana/php-logic#2]
```
function kebalik($input){

		for ($i= count($input)-1; $i>=0; $i--) { 
		print($input[$i]."</br>");
	}
	}
	echo kebalik($input);
```

karena di dalam fungsi sudah ada echo untuk menampilkan hasilnya. maka ketika pemanggilan fungsi tidak diperlukan echo lagi

**Comment by renaldypermana** [comment]
![image](https://user-images.githubusercontent.com/37020760/66109087-20655600-e5ee-11e9-80f6-918270f5f62e.png)
![image](https://user-images.githubusercontent.com/37020760/66109140-396e0700-e5ee-11e9-8d5c-7e1b1335339d.png)
